### ISSUE TITLE
Add support for Bluetooth as well as USB connected PFx Bricks

### ISSUE THREAD

**Issue by michaelgale** [fx-bricks/pfx-brick-py#1]
Adapt the API to scan for PFx Bricks using BLE.  Abstract the message parsing to work with USB or BLE devices.   Add a dependancy for the [bleak](https://github.com/hbldh/bleak) cross-platform BLE python module.

**Comment by LasseD** [comment]
> Add a dependancy for the bleak cross-platform BLE python module.

I'm looking forward to that enhancement.

I expect to get time to test this library on MAC next weekend. I could not get it to work last time I tried (late 2020) due to stale dependencies. Hopefully I will have more success this time.

**Comment by michaelgale** [comment]
@LasseD I’ve got most of it working now with BLE. Its not the most elegant implementation since Ive had to duplicate methods due to the `async / await` requirements of the `bleak` module.  In any case, it does basically work and reproduces the same functionality as USB connected bricks.  It also adds support for the PFx Brick’s notification mechanism.  That is, the brick can be configured to asynchronously send notifications for events, e.g. motor speed changes, audio playback events, etc.  I need to do a bit more testing, but should hopefully commit some changes very soon.

**Comment by michaelgale** [comment]
@LasseD FYI, all my testing has been with macOS 10.15. It looks like `bleak` does have a decent CoreBluetooth backend layer.

**Comment by michaelgale** [comment]
A new release v.0.7.0 adds support for BLE connected access to PFx Brick with the same functionality as USB.

**Comment by LasseD** [comment]
> @LasseD FYI, all my testing has been with macOS 10.15. It looks like `bleak` does have a decent CoreBluetooth backend layer.

Hi Michael,

Can you please tell me which libraries you have imported to make this work?

I have imported hidapi, bleak and pxfbrick on python3 using pip (pip install pfxbrick etc.), and also cloned the source and tried to run the sample files. Unfortunately every attempt at making this run results in the same error:


```

Traceback (most recent call last):
  File "tests/test_action.py", line 7, in <module>
    from pfxbrick import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pfxbrick/__init__.py", line 16, in <module>
    from .pfxexceptions import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pfxbrick/pfxexceptions.py", line 26, in <module>
    import hid
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/hid/__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

```

The easiest way to get the error is to follow the instructions from the README.md: 

```
$ python
>>> import pfxbrick

```

**Comment by michaelgale** [comment]
@LasseD I tried to repeat your error and I was surprised that it happened to me too!  I use anaconda to manage my python environments and have one just for PFx Brick development.  This environment used to work a few weeks ago, and now I get the same error for not being able to load the `hid` libraries.

I did get it to work by using `brew` (a really useful package manager for macOS).  I ran `brew install hidapi`.  I'm guessing there have been some system updates that required a lot of libraries to be updated.  `brew` ran for a couple of minutes updating a lot of packages.  Afterwards, my python environment worked fine.

**Comment by LasseD** [comment]
Thanks for helping me out with this @michaelgale .

I have installed hidapi using brew as you recommend, which lead to the same error. I uninstalled hidapi using pip and reinstalled using brew. Testing by simply typing "import pfxbrick" in a python3 console results in the error:

```
>>> import pfxbrick
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pfxbrick import *
  File "../pfxbrick/__init__.py", line 16, in <module>
    from .pfxexceptions import *
  File "../pfxbrick/pfxexceptions.py", line 26, in <module>
    import hid
ModuleNotFoundError: No module named 'hid'
```


I tried installing hid using brew, but it does not know of it. Then I tried using pip and now I'm back to the old error:


```
>>> import pfxbrick
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pfxbrick import *
  File "../pfxbrick/__init__.py", line 16, in <module>
    from .pfxexceptions import *
  File "../pfxbrick/pfxexceptions.py", line 26, in <module>
    import hid
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/hid/__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
```

Trying using pfxbrick installed using pip (rather than running from a repository) results in hidapi being installed using pip as it is marked as a dependency, which causes the error from my last message.


Did you use pip to install hid?

**Comment by michaelgale** [comment]
@LasseD I think the differences we observe come down to how we use python.  It looks like you use the builtin macOS python interpreter which has its system libraries in `/Library/Frameworks...` 

In any case, since I don't like using the default python interpreter and use multiple python environments depending on what I'm working on, I use `anaconda` to create and use multiple python environments.  These virtual environments allow you to create specialized lightweight python environments with different packages and dependancies.

Can you clarify which version of macOS you are using?  Also, do you have Xcode installed?  

If you want to use conda, you can use this recipe to create and build an python environment and install the pfx-brick-py package:

```shell
$ conda env create -f environment.yml
$ conda activate pfxtest
$ pip install -r requirements.txt
$ python setup.py install
```

The `environment.yml` is in the root of this repository.

In any case, your python interpreter is complaining because it cannot find the `hidapi` binary libraries in systems's library path.  The easiest way to install these libraries is with `brew`, but failing that, you would have to build them from source from the `hidapi` GitHub repository and that would require you having Xcode installed for the C compilers and toolchain.

You are running into a classic library dependency issue.  The missing element in your environment is `hidapi`.  Since macOS does not have a builtin package manager and developer tools; tools like `brew` and `macports` have become the defacto alternative package managers for macOS.  I would try to install [hidapi](https://formulae.brew.sh/formula/hidapi) using brew again and try to see where it installs the library.  It should be in `/usr/local/lib` as `libusb-1.0.0.dylib`

You should check your python system path as follows:

```python
>>> import sys
>>> sys.path
['/Library/Frameworks/Python.framework/Versions/3.8/bin']
```

If you don't see `/usr/local/lib` in the python sys.path, then you can append it as follows:

```python
>>> sys.path.append('/usr/local/lib')
>>> # then try to import hidapi
>>> import hid
```
