### ISSUE TITLE
Bluetooth connection not working.

### ISSUE THREAD

**Issue by aholzel** [fx-bricks/pfx-brick-py#2]
I am having trouble getting the connection setup and than send commands to the pfxbrick. 

I am running the latest release (0.8.5) on a raspberry PI 3b. The problem seems to be in the checking of the Bluetooth connection. If I run the example script to connect via Bluetooth  and than turn on the lights I can see on the CLI via 'bluetoothctl' that the connection is made with the brick, but for some reason after that nothing happens anymore. I don't get any errors that can help... it just keeps printing out:
```
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...
```
until the timeout is hit. It looks like the connection is set-up and than removed again

Also if for some reason the Bluetooth connection is already set up between the Pi and the PFX brick the script keeps scanning for bricks, it doesn't take into account that there might already be a connection established. 

I do get the following "general" errors when I try the bluetooth connection with `verbose=True`  set on the `ble_device-scanner` function:
```
Scanning...
/usr/local/lib/python3.9/dist-packages/pfxbrick/pfxble.py:88: FutureWarning: This method will be removed in a future version of Bleak. Use the `discovered_devices` property instead.
  devices = await scanner.get_discovered_devices()
Found 9 advertising devices
 1. UUID=00:E9:51:xx:yy:zz                    "00-E9-51-xx-yy-zz"
 2. UUID=6E:F3:BD:xx:yy:zz                    "6E-F3-BD-xx-yy-zz"
 3. UUID=5D:FC:E6:xx:yy:zz                    "5D-FC-E6-xx-yy-zz"
 4. UUID=44:31:B7:xx:yy:zz                    "AC692x_BLE"
 5. UUID=30:88:3B:xx:yy:zz                    "30-88-3B-xx-yy-zz"
 6. UUID=CD:F3:43:xx:yy:zz                    "OKIN-458470"
 7. UUID=7D:3D:6D:xx:yy:zz                    "7D-3D-6D-xx-yy-zz"
 8. UUID=80:1F:12:xx:yy:zz                    "PFx Brick 16 MB"
 9. UUID=30:95:E3:xx:yy:zz                    "30-95-E3-xx-yy-zz"
Found PFx Brick 16 MB
Found 1 PFx Bricks
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...
/usr/local/lib/python3.9/dist-packages/pfxbrick/pfxble.py:121: FutureWarning: is_connected has been changed to a property. Calling it as an async method will be removed in a future version
  x = await client.is_connected()
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...
Discovering device 80:1F:12:xx:yy:zz "PFx Brick 16 MB"...

```

**Comment by michaelgale** [comment]
Thanks for finding this and for contributing your PR.  Your changes were incorporated into a new release v.0.8.6 along with some other changes and improvements.
